# This is a basic workflow to help you get started with Actions

name: CI

env:
  bds_version: 1.16.201.02
  nim_version: 1.4.2

on:
  push:
    branches: [ 💥 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: Element-0/chakra
      - name: Download rcedit.exe
        uses: robinraju/release-downloader@v1
        with:
          repository: electron/rcedit
          latest: true
          fileName: rcedit-x64.exe
          out-file-path: ${{ runner.tool_cache }}/rcedit
      - name: Setup rcedit
        run: |
          Rename-Item ${{ runner.tool_cache }}\rcedit\rcedit-x64.exe ${{ runner.tool_cache }}\rcedit\rcedit.exe
          Write-Output "${{ runner.tool_cache }}\rcedit" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
      - name: Install nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim_version }}
      - name: Install dependencies
        run: |
          $cfg = New-Item -Path (Join-Path $env:APPDATA "nimble\nimble.ini") -Force
          Write-Output ("::group::Add ElementZero packages source: " + $cfg)
          Write-Output "[PackageList]" 'name = "ElementZero"' 'url = "https://element-0.win/packages.json"' | Out-File -FilePath $cfg -Encoding utf8 -Append
          Write-Output "::endgroup::"
          Write-Output "::group::Refresh nimble database"
          Start-Process -Wait -NoNewWindow nimble.exe -ArgumentList "refresh"
          Write-Output "::endgroup::"
          Write-Output "::group::Install dependencies"
          Start-Process -Wait -NoNewWindow nimble.exe -ArgumentList "install -d"
          Write-Output "::endgroup::"
      - name: B
