name: CI

env:
  bds_version: 1.16.201.02

on:
  push:
    branches: [ 💥 ]
  pull_request:
    branches: [ 💥 ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
      - name: Install nim
        uses: jiro4989/setup-nim-action@v1
      - name: Install dependencies
        run: |
          echo "::group::Refresh nimble database"
          nimble refresh
          echo "::endgroup::"
          echo "::group::Install nimake"
          nimble install https://github.com/codehz/nimake@#v0.4.6
          echo "::endgroup::"
          echo "::group::Install winim"
          nimble install winim
          echo "::endgroup::"
      - name: Dump targets
        run: nimake dump
      - name: Build sqlite3
        run: nimake build -v:5 sqlite3
      - name: Run tests
        run: nimake build -v:5 test
      - name: Build default target
        run: nimake build -v:5
      - name: Build pdbparser
        run: nimake build -v:5 pdbparser
      - name: Parse bedrock_server.pdb and generate database
        run: |
          cd dist
          echo "::group::Downloading"
          curl.exe -#Lo bedrock_server.zip https://minecraft.azureedge.net/bin-win/bedrock-server-${{ env.bds_version }}.zip
          echo "::endgroup::"
          echo "::group::Extracting"
          tar.exe xf bedrock_server.zip bedrock_server.pdb
          echo "::endgroup::"
          echo "::group::Parsing"
          .\pdbparser.exe bedrock_server.pdb --database:bedrock_server.db
          echo "::endgroup::"
          echo "::group::Database info"
          Get-ItemProperty bedrock_server.db | Format-List
          echo "::endgroup::"